# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discount_Collection', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
